name: ve_vod_controls
description: "基于ve_vod封装的视频播放器，携带控制器"
version: 1.0.3
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/ve_vod_controls
issue_tracker: https://github.com/LiWenHui96/ve_vod_controls/issues
topics:
  - volcengine
  - video
  - controls

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  marquee: ^2.2.3
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  screen_brightness: ^1.0.1
  ve_vod: ^1.42.3-5
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.ve.vod.controls
        pluginClass: VeVodControlsPlugin
      ios:
        pluginClass: VeVodControlsPlugin
