name: ve_vod_controls
description: "The Flutter plugin providers volcengine tt sdk native APIs to implement video player. 集成火山云视频点播原生SDK。"
version: 0.0.1
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/ve_vod_controls
issue_tracker: https://github.com/LiWenHui96/ve_vod_controls/issues
topics:
  - 火山云
  - TTSDK
  - video

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ve_vod: ^1.42.3-1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.ve.vod.controls
        pluginClass: VeVodControlsPlugin
      ios:
        pluginClass: VeVodControlsPlugin
