name: ve_vod_controls
description: "基于ve_vod封装的视频播放器，携带控制器"
version: 1.0.8
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/ve_vod_controls
issue_tracker: https://github.com/LiWenHui96/ve_vod_controls/issues
topics:
  - volcengine
  - video
  - controls

environment:
  sdk: ^3.5.0
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  marquee: ^2.3.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.4
  screen_brightness: ^2.1.2
  ve_vod: ^1.45.3-1
  wakelock_plus: ^1.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.ve.vod.controls
        pluginClass: VeVodControlsPlugin
      ios:
        pluginClass: VeVodControlsPlugin
